// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJxI4u5x_4e0JlcypNUiU1GcqrollUB0',
    appId: '1:1071680051297:web:cffbfcaf1232d969967220',
    messagingSenderId: '1071680051297',
    projectId: 'my-todo-ubit-project',
    authDomain: 'my-todo-ubit-project.firebaseapp.com',
    storageBucket: 'my-todo-ubit-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDtUYfDVCinZyVzHUycmImAeRLugjL6D0',
    appId: '1:1071680051297:android:5451c32237268616967220',
    messagingSenderId: '1071680051297',
    projectId: 'my-todo-ubit-project',
    storageBucket: 'my-todo-ubit-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdJ8jy6SGQvmlSZMwt9Ih9Iw3whfpxrQ',
    appId: '1:1071680051297:ios:a22b607820ca8d1b967220',
    messagingSenderId: '1071680051297',
    projectId: 'my-todo-ubit-project',
    storageBucket: 'my-todo-ubit-project.appspot.com',
    iosClientId: '1071680051297-gm3fkras74n3hquogb4ke3fhljf5k6g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtdJ8jy6SGQvmlSZMwt9Ih9Iw3whfpxrQ',
    appId: '1:1071680051297:ios:983b3312e4e534df967220',
    messagingSenderId: '1071680051297',
    projectId: 'my-todo-ubit-project',
    storageBucket: 'my-todo-ubit-project.appspot.com',
    iosClientId: '1071680051297-t79iingnoqfkol59ub3no77lhh4bao49.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
